apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: airtrail-hpa
  namespace: "{{ namespace | default('default') }}"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: airtrail-deployment
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 75