apiVersion: v1
kind: Service
metadata:
  name: airtrail-service
  labels:
    app: airtrail
  namespace: "{{ namespace | default('default') }}"
spec:
  type: LoadBalancer
  selector:
    app: airtrail
  ports:
    - port: 80         # Porta PÃºblica (Browser)
      targetPort: 3000 